In [1]:
import pandas as pd
from rake_nltk import Rake
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
folder= './Data'

In [4]:
df_game = pd.read_csv(folder+'/BggGames.csv')

df_game.head(10)

,bgg_id,name,year,game_type,designer,artist,publisher,min_players,max_players,min_players_rec,...,stddev_rating,bayes_rating,complexity,language_dependency,bga_id,dbpedia_id,luding_id,spielen_id,wikidata_id,wikipedia_id
0,1,Die Macher,1986.0,5497,1,"12517,4959","133,2,2726,15108,39249,11652,5382,8147",3.0,5.0,4.0,...,1.58914,7.14730,4.3347,1.152778,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Dragonmaster,1981.0,5497,8384,12424,"64,20",3.0,4.0,3.0,...,1.44458,5.80514,1.9630,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Samurai,1998.0,5497,2,11883,"17,133,267,29,7340,7335,41,2973,4617,1391,8291...",2.0,4.0,2.0,...,1.18374,7.24612,2.4916,1.000000,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Tal der Könige,1992.0,NaN,8008,2277,37,2.0,4.0,2.0,...,1.23365,5.70180,2.6667,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Acquire,1964.0,5497,4,"12658,18317","92,5,4871,3082,858,2962,5392,4668,38,4622,7107",2.0,6.0,3.0,...,1.33541,7.16306,2.5057,1.090278,NaN,NaN,NaN,NaN,NaN,NaN
5,6,Mare Mediterraneum,1989.0,NaN,5,5,6,2.0,6.0,2.0,...,1.64101,5.55218,3.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,Cathedral,1978.0,4666,1335,36624,"6421,4089,672,786,155,148,327,93,17832,35425",2.0,2.0,2.0,...,1.32292,6.15873,1.8022,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,8,Lords of Creation,1993.0,NaN,6,36807,"4675,7",2.0,5.0,2.0,...,1.28950,5.57732,2.4000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9,El Caballero,1998.0,5497,"7,8",74,"267,133,3",2.0,4.0,2.0,...,1.42193,5.96117,3.1905,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,10,Elfenland,1998.0,5499,9,74,"8,267,6818,18852,3395,3",2.0,6.0,3.0,...,1.25196,6.50998,2.1613,1.000000,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df_game= df_game.sort_values('rank')
df_game.head
(50)

,bgg_id,name,year,game_type,designer,artist,publisher,min_players,max_players,min_players_rec,...,stddev_rating,bayes_rating,complexity,language_dependency,bga_id,dbpedia_id,luding_id,spielen_id,wikidata_id,wikipedia_id
95480,314079,Galamons,2020.0,NaN,NaN,NaN,4,2.0,4.0,2.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95481,314080,"Your Quest, Should You Choose to Accept It!",2020.0,NaN,88510,88510,2456,2.0,8.0,2.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95482,314081,おとひめクエスト (Otohime Quest),2015.0,NaN,80275,"128452,128451","27447,29514",2.0,2.0,2.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95483,314086,First Monday in October,2021.0,NaN,128453,NaN,37622,2.0,4.0,2.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95484,314088,Agropolis,2020.0,NaN,"73472,68355,91357",68355,26991,1.0,4.0,1.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95485,314113,落書きプラネット (Rakugaki Puranetto),2012.0,NaN,65503,NaN,29166,3.0,6.0,3.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95486,314126,Clue: Downton Abbey,2019.0,NaN,NaN,NaN,51,2.0,6.0,2.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95487,314169,Crossroads,2020.0,NaN,53801,NaN,19114,3.0,5.0,3.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95488,314170,2 Minutes to Midnight,2021.0,NaN,99353,NaN,3929,2.0,2.0,2.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95489,314171,Dive Master Card Game,2020.0,NaN,128504,128504,46110,2.0,5.0,2.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95490,314172,Battle Peak,2021.0,NaN,116740,116740,4,2.0,4.0,2.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95491,314174,Disaster Blaster,2020.0,NaN,128506,128505,4,2.0,6.0,2.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95492,314208,"Lances and Steel: The Battle of Mokra, Septemb...",2020.0,NaN,812,85503,17180,1.0,2.0,1.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95493,314239,In Cold and Dicey Waters,2020.0,NaN,NaN,NaN,1001,2.0,4.0,2.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95494,314243,"Warhammer 40,000 (Ninth Edition)",2020.0,NaN,NaN,NaN,26,2.0,6.0,2.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95495,314248,Go For Broke!: A World War II Miniatures Skirm...,2020.0,NaN,NaN,NaN,4,2.0,8.0,2.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95496,314279,Malady,2020.0,NaN,101050,NaN,1001,2.0,3.0,2.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95497,314311,Stone after Stone: Olympic Curling,2012.0,NaN,8869,NaN,6597,1.0,2.0,1.0,...,0.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95498,314395,Pocket Detective №2,2020.0,NaN,57182,NaN,"31717,34801",1.0,6.0,1.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95499,314402,Ubongo Mini Demo,2015.0,NaN,988,"56983,12056,12380",37,1.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95500,314440,"War Among the Gods, Battle for Olympus",2021.0,NaN,NaN,NaN,46132,1.0,6.0,1.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95501,314459,Wer kommt an's Ziel im Bleyle Spiel,NaN,NaN,NaN,NaN,46134,2.0,4.0,2.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95502,314461,The Deadly Woods: The Battle of the Bulge,2021.0,NaN,484,"2652,11856,1893",18698,1.0,2.0,1.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95503,314462,Swack,2020.0,NaN,47001,NaN,1001,2.0,2.0,2.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95504,314469,10-10,2019.0,NaN,117256,NaN,1001,3.0,4.0,3.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95505,314470,不器用な２人 (They Two Are Clumsy),2019.0,NaN,88412,NaN,1001,2.0,2.0,2.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95506,314485,"TiRoBEx: Tiny Robots, Big Explosions",2017.0,NaN,43372,NaN,15317,2.0,2.0,2.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95507,314489,Zirkus Bumsti,NaN,NaN,NaN,NaN,46137,2.0,6.0,2.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95508,314490,Weihnachtstellereisbahn,NaN,NaN,NaN,NaN,3320,2.0,6.0,2.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95509,314491,Meadow,2020.0,NaN,89488,128605,7466,1.0,4.0,1.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95510,314495,Tha-Ga-Kaffee-Spiel - Abenteuerliche Reise ein...,1931.0,NaN,NaN,NaN,"46139,46138",2.0,6.0,2.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95511,314497,Albastini Card Game,2020.0,NaN,NaN,NaN,4,2.0,9.0,2.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95512,314499,Wir besuchen Bremen,NaN,NaN,NaN,NaN,46140,2.0,6.0,2.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95513,314503,CODEX Naturalis,2020.0,NaN,120680,128606,19260,2.0,4.0,2.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95514,314517,Monopoly: Folkestone,2020.0,NaN,1268,NaN,32781,2.0,6.0,2.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95515,314525,Space Dogs,2018.0,NaN,NaN,NaN,NaN,2.0,4.0,2.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95516,314529,Partout,2020.0,NaN,NaN,NaN,NaN,3.0,6.0,3.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95517,314530,Iwari: Deluxe Edition,2020.0,NaN,86,98928,"32922,30155,38448",2.0,5.0,2.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95518,314541,Curse of The Necronomicon,2020.0,NaN,NaN,NaN,2456,2.0,4.0,2.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95519,314542,Escape Room in a Box: The Walking Dead,2020.0,NaN,"12874,128633,1496",NaN,93,2.0,8.0,2.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95520,314543,Clue: Card Game,2018.0,NaN,3,3,51,3.0,4.0,3.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95521,314546,Gelato,2020.0,NaN,95126,NaN,34218,2.0,5.0,2.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95522,314549,Scene It?: Game Pack – Movie Edition,2005.0,NaN,"1885,1553","1885,1553",93,2.0,12.0,2.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95523,314550,Campeones de Midgard: Big Box,2020.0,NaN,57793,"27926,24841","24883,26427",2.0,4.0,2.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95524,314577,"Pacific War: The Struggle Against Japan, 1941-...",2021.0,NaN,152,NaN,52,2.0,2.0,2.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95525,314580,Hamburg,2021.0,NaN,4958,6076,47,2.0,5.0,2.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95526,314582,Amsterdam,2021.0,NaN,4958,"6076,11898",47,2.0,4.0,2.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95527,314671,Give Me the Brain: Superdeluxe Edition,2015.0,NaN,61,280,12,3.0,8.0,3.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95528,314672,Stilicho: Last of the Romans,2020.0,NaN,105224,"11856,50619",33711,1.0,1.0,1.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95529,314730,더 갤러리스트,2020.0,NaN,12396,64844,39249,1.0,4.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
df_game.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 95530 entries, 66090 to 95529
Data columns (total 38 columns):
bgg_id                 95530 non-null int64
name                   95530 non-null object
year                   86698 non-null float64
game_type              20987 non-null object
designer               82110 non-null object
artist                 38370 non-null object
publisher              95520 non-null object
min_players            93686 non-null float64
max_players            90176 non-null float64
min_players_rec        93686 non-null float64
max_players_rec        90176 non-null float64
min_players_best       93686 non-null float64
max_players_best       90176 non-null float64
min_age                73935 non-null float64
min_age_rec            843 non-null float64
min_time               75400 non-null float64
max_time               75400 non-null float64
category               93578 non-null object
mechanic               80331 non-null object
cooperative            95530 non-null int64
compilation            95530 non-null int64
compilation_of         585 non-null object
family                 53487 non-null object
implementation         4188 non-null object
integration            2778 non-null object
rank                   19150 non-null float64
num_votes              95528 non-null float64
avg_rating             70038 non-null float64
stddev_rating          95528 non-null float64
bayes_rating           19406 non-null float64
complexity             41202 non-null float64
language_dependency    763 non-null float64
bga_id                 0 non-null float64
dbpedia_id             0 non-null float64
luding_id              0 non-null float64
spielen_id             0 non-null float64
wikidata_id            0 non-null float64
wikipedia_id           0 non-null float64
dtypes: float64(24), int64(3), object(11)
memory usage: 28.4+ MB

In [17]:
df_rank = pd.read_csv(folder+'/BggGames.csv', usecols= ['bgg_id','name','category','mechanic','rank'])
df_rank.head(10)

,bgg_id,name,category,mechanic,rank
0,1,Die Macher,"1021,1026,1001","2916,2080,2012,2072,2040,2020",262.0
1,2,Dragonmaster,"1002,1010",2009,3473.0
2,3,Samurai,"1009,1035","2080,2040,2004,2002",199.0
3,4,Tal der Könige,1050,"2001,2080,2012,2004",4584.0
4,5,Acquire,1021,"2040,2910,2900,2911,2005,2002",254.0
5,6,Mare Mediterraneum,"1015,1008",2072,9415.0
6,7,Cathedral,1009,"2043,2048,2060,2002",1776.0
7,8,Lords of Creation,"1015,1010",2011,7799.0
8,9,El Caballero,1020,"2080,2002",2521.0
9,10,Elfenland,"1010,1097","2041,2040,2081,2078",972.0

In [18]:
df_rank.describe()

              bgg_id          rank
count   95530.000000  19150.000000
mean   118786.068827   9576.023864
std     97873.192203   5528.783114
min         1.000000      1.000000
25%     27467.250000   4789.250000
50%    102791.500000   9578.000000
75%    197823.000000  14360.750000
max    314730.000000  19178.000000

In [21]:
df_rank[df_rank['rank']<= 19178]

,bgg_id,name,category,mechanic,rank
0,1,Die Macher,"1021,1026,1001","2916,2080,2012,2072,2040,2020",262.0
1,2,Dragonmaster,"1002,1010",2009,3473.0
2,3,Samurai,"1009,1035","2080,2040,2004,2002",199.0
3,4,Tal der Könige,1050,"2001,2080,2012,2004",4584.0
4,5,Acquire,1021,"2040,2910,2900,2911,2005,2002",254.0
...,...,...,...,...,...
94264,308565,Roll n Cook,1120,"2072,2055,2020,2082",9166.0
94348,308989,Bristol 1350,"1039,1017,1035,1030,1031","3002,2072,2950,2891,2685,2820",12982.0
94607,310100,Nemesis: Lockdown,"1022,1024,1047,1016","2023,2072,2891,2011,2685,2820,2814,2015",10340.0
95212,312804,Pendulum,1021,"2834,2020,2015,2082,2933",13472.0
95424,313850,Escape The Night: The Board Game,"1022,1010,1024,1064,1026","2916,2072,2676,2685,2820,2686,2663,2017",19178.0

In [22]:
nan_rows = df_rank[df_rank.isnull().any(1)]
nan_rows

,bgg_id,name,category,mechanic,rank
20,21,Gateway to the Stars,"1015,1020,1016,1019",NaN,15901.0
31,32,Buffalo Chess,"1009,1055",NaN,7376.0
34,37,Dragon Masters,"1010,1019",NaN,14133.0
35,38,Runes,"1039,1025",NaN,10339.0
36,39,Darkover,"1023,1010,1093",NaN,16960.0
...,...,...,...,...,...
95525,314580,Hamburg,"1002,1029,1021","2072,2040",NaN
95526,314582,Amsterdam,1017,"2001,2041,2072,2040,2081,2007,2004",NaN
95527,314671,Give Me the Brain: Superdeluxe Edition,"1002,1079,2481","2001,2012,2072,2040",NaN
95528,314672,Stilicho: Last of the Romans,"1050,1019","2018,2072,2040,2078,2819",NaN
95529,314730,더 갤러리스트,1021,"2013,2910,2004,2082",NaN

In [24]:
nan_rows_cat = nan_rows[nan_rows['category'].isnull()]
nan_rows_cat

,bgg_id,name,category,mechanic,rank
456,518,Cat vs. Mouse,NaN,NaN,NaN
523,600,Die Weinhändler,NaN,"2040,2007,2078",17249.0
755,868,Atlantis,NaN,NaN,NaN
760,873,Offline,NaN,2002,14503.0
790,910,Kunst Stücke,NaN,"2676,2040,2002",6811.0
...,...,...,...,...,...
95470,314032,Levitation: Masters of Magic,NaN,"2072,2856,2984,2875,2048,2015,2082",NaN
95471,314040,Pandemic Legacy: Season 0,NaN,"2001,2023,2040,2824,2078,2004,2015",NaN
95485,314113,落書きプラネット (Rakugaki Puranetto),NaN,2039,NaN
95513,314503,CODEX Naturalis,NaN,NaN,NaN
95521,314546,Gelato,NaN,"2072,2004,2686,2935",NaN